name: Build and Push Docker Image

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod


env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: myapp
  


jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Verify Repository Structure
      run: |
        pwd
        ls -la
        find . -name ./src/MyApp.Api/Dockerfile


    - name: Configure AWS Credentials
      if: github.event_name != 'pull_request'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}


    - name: Login to Amazon ECR
      if: github.event_name != 'pull_request'
      uses: aws-actions/amazon-ecr-login@v2


    - name: Generate Image Tags
      id: image
      run: |

        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)

        if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
          IMAGE_TAG=dev-${SHORT_SHA}
        elif [ "${{ github.event.inputs.environment }}" == "qa" ]; then
            IMAGE_TAG=qa-${SHORT_SHA}
        elif [ "${{ github.event.inputs.environment }}" == "uat" ]; then
            IMAGE_TAG=uat-${SHORT_SHA}
        elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            IMAGE_TAG=prod-v${{ github.run_number }}
        else
          IMAGE_TAG=${SHORT_SHA}
        fi

        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

        echo "Generated Tag : $IMAGE_TAG"


    - name: Build Docker Image
      run: |

        docker build \
        -f ./src/MyApp.Api/Dockerfile \
        -t $ECR_REPOSITORY:$IMAGE_TAG .


    - name: Tag Docker Image
      if: github.event_name != 'pull_request'
      run: |

        docker tag \
        $ECR_REPOSITORY:$IMAGE_TAG \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG


    - name: Push Image to ECR
      if: github.event_name != 'pull_request'
      run: |

        docker push \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG


# =====================================================
# Environment Deployment Jobs
# =====================================================

  deploy-dev:

    needs: build

    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.environment == 'dev'

    environment:
      name: dev

    runs-on: ubuntu-latest

    steps:

    - name: Deploy DEV
      run: |
        
        echo "Deploying DEV"
        echo "Image Tag : $IMAGE_TAG"



  deploy-qa:

    needs: build

    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.environment == 'qa'

    environment:
      name: qa

    runs-on: ubuntu-latest

    steps:

    - name: Deploy QA
      run: |
        echo "Deploying QA"
        echo "Image Tag : $IMAGE_TAG"



  deploy-uat:

    needs: build

    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.environment == 'uat'

    environment:
      name: uat

    runs-on: ubuntu-latest

    steps:

    - name: Deploy UAT
      run: |
        
        echo "Deploying UAT"
        echo "Image Tag : $IMAGE_TAG"



  deploy-prod:

    needs: build

    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.environment == 'prod'

    environment:
      name: prod

    runs-on: ubuntu-latest

    steps:

    - name: Deploy PROD
      run: |
        echo "Deploying PROD"
        echo "Image Tag : $IMAGE_TAG"
        
